### PR TITLE
Add minified version of js and css. Order 1=>socialcalcconstants.js 2…

### PR DESCRIPTION
**Pull request by willhallonline**
Added minified versions of both JS and CSS. JS is in order as listed in Sheetnode module.

### CODE REVIEW

**Comment by willhallonline** [comment]
OK I will look at doing this and then re-apply. Would it also be better to separate out into a different directory when saving?

**Comment by infojunkie** [comment]
This codebase is pretty old and predates the standard JS practices that have evolved, e.g. folder structure. I don't think it's realistic to fix everything all at once, but whatever change is made should indeed bring us closer to follow the current practices.

**Comment by willhallonline** [comment]
Have added a gulpfile for creating minified versions of JS and CSS which can automate process for any updates now.

**Comment by infojunkie** [comment]
Also need the package.json file to download the `gulp` dependencies, no?

**Comment by willhallonline** [comment]
Added a package.json. Could do with re-running on your install too. Obviously could do with some versions and a README.md, but don't want to add too much into this pull request.

**Pull request merged**
